### ISSUE TITLE
User can sort their entries by date created

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/code-journal#9]
## 💰 Motivation

When a user is creating a new entry, a date is automatically applied based on time of submit. User will also be able to view  oldest-newest entries or newest-oldest(default)

## 📐 Plan

Display the value of chosen date on each entry. 
Allow option of sorting entries on page, by newest or by oldest

## 🖼️ Wireframes

![user can view their entries mobile](https://i.gyazo.com/4e3651c46264a8f27e68d96fb9b74883.png)

## ✅ Task List

- [x] Add new property 'date' (.date().substr(0,10) to object property when clicking submit.
- [x] Attach a new attribute to each li the value of entry.date (parameter)
- [x] Add a new div with child ul on our entries page w/ class hidden on div
- [x] Create a new dom element (h6) to return from entryDOM 
- [x] Give the h6 dom element the text value of the date property (.date().substr(0,10));
- [x] Attach the new dom element to the row containing the title and icon 
- [x] Create list with all string values made from 'date property' from all entries 
- [x] Create a button icon that lets you sort from old dates to new dates
- [x] Create a button icon that returns old div (new dates to old dates) default.
- [x] Add functionality to each button when clicked make a new array using .reverse() on the list of values and data-view="entries" becomes hidden and new div removes hidden class.
- [x] Loop through each li,  if the li attribute date matches the ordered array value, append the li to the new ul.
- [x] Switching views makes the new div have the class hidden. and entries removes hidden
- [x] Check that the entries list looks good on both mobile and desktop screens.
